---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ai-platform-secrets
  namespace: ai-platform
spec:
  encryptedData:
    llm-api-key: AgCvDk2Sg2Mr2BYJSq5ZHii718yglqToqBVOJSZ+MZk/Hk1eYHYnTG7DoxHUXjxKTKoJe/aklBkCm+1w17Hl7whwcDNy4A4eJKRrj1S7BgIZiacZdwpBruR1a0zg33tmSiiZD+U2d2kx2p5YIVrFSrCixt2wakzpeDxjBOmHflIGBeGBtWizOfiR5BugSj90qNxLNt7tpVviZDZHuK7hf355s90mpOKMXBBnCaeRKWZofkdzUZ8v0hcY2Aml4HFzind3TrnmnduJnJ59fnebCKoBPXsYSJQK7L1BlyV2/BZihzWfdfOKMI1+O1U5ZA50mzJ03EYv5eGA6jMWdmTQRKSWfeM6KHI878ScV0tL3sLLkbuJOGjviyD7npBgGvkZwOGIa8F6plwXZfIY3Nq1D013QpMGUZbY1+anmkFu9xLMVuPaSppNhTd4Z5RgADsGMRVt8B0M/ZzMa/fRisT7Kktl6MviTrdhk0ri38B6jDZXab/PhH+OSQ6oGSyckRM9xoaYuLIjOBvsU+RuqLV37tEI1CNGmqfW2JWK1zq18wlJCr3XjzhilYl9t6esM6YwrgUshnP11rKfHhXMxRy+C2HWXYaNqUiWZVQVlmYu3Yyvu54kJvo3QSV2toCAF0zhZG+YgyYQD3X8i7EE/7FX4Grfcyi11St38aCzbmbst0oWMRbNeZeqMh/8YFHDWdVOH2dq7GorZvQuJjbgEIrPInaXxz20932XoiD9UcagjxSnLjmZoFomdplQQpA/m1Wf2TlUAIwfEDYPnw==
  template:
    metadata:
      creationTimestamp: null
      name: ai-platform-secrets
      namespace: ai-platform
