apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lakunzy7/AI-Customer-Support-Platform.git
    targetRevision: main
    path: k8s/sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
