global:
  env: production

api:
  replicas: 2
  image:
    repository: ghcr.io/lakunzy7/ai-platform
    tag: latest
    pullPolicy: IfNotPresent
  logLevel: info
  service:
    type: ClusterIP
  llm:
    baseUrl: "https://api.groq.com/openai/v1"
    model: "llama-3.3-70b-versatile"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPU: 70
    targetMemory: 80
  pdb:
    enabled: true
    minAvailable: 1
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/rate-limit: "100"
    hosts:
      - host: ai-platform.local
        paths:
          - path: /
            pathType: Prefix
  canary:
    enabled: false
    replicas: 1
    weight: 10  # % of traffic to canary
    model: "llama-3.3-70b-versatile"
    image:
      repository: ghcr.io/lakunzy7/ai-platform
      tag: latest

redis:
  image:
    repository: redis
    tag: 7-alpine
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

postgresql:
  image:
    repository: postgres
    tag: 16-alpine
  auth:
    username: aiplatform
    password: aiplatform
    database: aiplatform
  storage:
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

seed:
  enabled: true

qdrant:
  image:
    repository: qdrant/qdrant
    tag: v1.12.5
  storage:
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
